version: "3.9"
services:
  app:
    container_name: thc
    image: thc
    build: ./
    ports:
      - "8300:80"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3300/thc_db?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=sample
      - SPRING_DATASOURCE_PASSWORD=sample

  db:
    image: 'mysql:5.7.34'
    container_name: db
    ports:
      - "3300:3300"
    environment:
#      - MYSQL_DATABASE: thc_db
      - MYSQL_USER=sample
      - MYSQL_PASSWORD:sample
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB=thc_db
#    volumes:
#      - db-data:/var/lib/mysql
#  volumes:
#    db-data: